name: Java CI con Maven

on:
  push:
    branches: [ main, Requerimientos3 ]
  pull_request:
    branches: [ main, Requerimientos3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Caché de dependencias de Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Compilar con Maven
      run: mvn -B package --file pom.xml

    - name: Ejecutar pruebas
      run: mvn test
